backend:
    name: github
    repo: DevByRayRay/jam-stack-gatsby-ecommerce-netlify-cms
    branch: master

# when using the default proxy server port
local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: product
    label: Product
    folder: content/products
    create: true
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "thumbnail", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: markdown }