backend:
    name: git-gateway

# when using the default proxy server port
local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: product
    label: Product
    folder: products
    create: true
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - {label: "Image", name: "thumbnail", widget: "image"}
      - { name: "body", label: "Body", widget: markdown }